# syntax=docker/dockerfile:1

FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN go test ./...
RUN CGO_ENABLED=0 go build -o /out/greeter ./cmd/greeter

FROM scratch
COPY --from=build /out/greeter /greeter
USER 65532:65532
ENTRYPOINT ["/greeter"]
