# syntax=docker/dockerfile:1
FROM node:22-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json ./
COPY packages/message-format/ packages/message-format/
RUN npm ci --omit=dev && node -e "setTimeout(() => {}, 3000)"
COPY src/ src/
COPY test/ test/
EXPOSE 8080
CMD ["node", "src/server.js"]
